### ISSUE TITLE
Duplicate calls suppressed

### ISSUE THREAD

**Issue by eriksundin** [Tealium/ios-library#16]
When enabling queue:ing and submitting a view, followed by an event call from a class I'm getting a:
```
TEALIUM 4.1.1c: Duplicate call from <MyViewController: 0x7aa31600> suppressed.
```
I was expecting these two calls to be different based on the call type. What conditions is the suppression evaluated on?

Thanks

**Comment by jalakoo** [comment]
Hey Erik,
Only calls where all the data points are of the exact same value should be suppressed by the duplicate call filter.  Could you paste the two separate track calls so we can test here?

Also, the second event call is triggering that Duplicate call warning, correct?

**Comment by ethyreal** [comment]
Erik,

We have identified and corrected the duplicate suppression problem and it will be in our next release.

Currently if you pass the same object to more than one track call within .25 seconds it is flagged as a duplicate.   

```objective-c
- (void) someHandler {
    
    [Tealium trackCallType:TealiumViewCall customData:nil object:self];
    
    [Tealium trackCallType:TealiumEventCall customData:nil object:self];
}
```
Until we get out next release out I can offer some work arounds.  
First you could extract the custom data from the object you were passing in and add it as the custom data for subsequent track calls and pass nil for the object argument like this:
```objective-c
- (void) someHandler {

    [Tealium trackCallType:TealiumViewCall
                customData:nil
                    object:self];
    
    // get the stored date for this object.
    NSMutableDictionary *customData = [Tealium customDataForObject:self];
    
    // if it doesn't contain all desired UDO Key/Values add some:
    customData["screen_title"] = self.title;
    customData["my_custom_key"] = @"my value";
    
    [Tealium trackCallType:TealiumEventCall
                customData:customData
                    object:nil];
}
```
Since the current duplicate checking keys off of object matching passing nil to object ensures the call goes through and loading the custom data up with the object's data you still get the same content into your track calls.

Another method would be to fire them with a quarter second delay one after the other like this:
```objective-c
- (void) fireMultipleTrackCalls {

    NSInteger numberOfTrackCalls = 4;

    NSInteger currentCallCount = 0;
    
    while (currentCallCount < numberOfTrackCalls) {
        
        currentCallCount++;
        
        NSInteger delay = .25 * currentCallCount;
        
        __weak NSObject *weakSelf = self;
        
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(delay * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            [Tealium trackCallType:TealiumEventCall
                        customData:nil
                            object:weakSelf];
        });
    }
}
```

**Comment by eriksundin** [comment]
Ops! Completely missed the responses above. Great, thanks for looking into it and fixing!

Regards,
Erik
