### ISSUE TITLE
iOS 8 Memory leak

### ISSUE THREAD

**Issue by iainsmith** [Tealium/ios-library#17]
Hi

We have a leak in our application that we have traced back to how iOS8 handles http keep-alive headers. See [here (for a discussion on AFNetowrking)](https://github.com/AFNetworking/AFNetworking/issues/2314) and [here](http://stackoverflow.com/a/25996971) for more details. This is a serious issue for us as we can leak 50mb of data in a typical user journey.

**Comment by ethyreal** [comment]
Thank you for the info.   We are in the process of moving our net code over to NSURLSession from NSURLConnection.  The session suite of classes to not seem to exhibit this problem.  We will have this ready for our next release, but if as suggested the problem is in the iOS SDK it is likely an Apple SDK update will correct the problem.

**Comment by iainsmith** [comment]
Are you sure NSURLSession does indeed fix this? The links I included suggest this issue is still present in NSURLSession.

**Comment by ethyreal** [comment]
Most of the examples listed in your links refer to using NSURLConnection.  There was a sample project exhibiting this behavior, but I have found this is only present in the simulator and iOS 8 devices this is not an issue.

I will keep investigating this further to ensure we don't have this problem in our next release.
