### ISSUE TITLE
Events sent on main thread

### ISSUE THREAD

**Issue by iainsmith** [Tealium/ios-library#19]
Hi Guys,

What is the reasoning for sending events through `[TealiumInternalConstants performBlockOnMainThread]`?

Profiling in instruments reveals that Tealium is the cause of slow down while scrolling our app.

![tealium_performance](https://cloud.githubusercontent.com/assets/993745/6622530/09f79fe4-c8d5-11e4-8f06-825aabe9a68f.jpg)

**Comment by ethyreal** [comment]
Hi @iainsmith ,

Our library runs almost everything within its own serial queue.  However whenever it needs to interact with an object from UKKit it is not safe to do so except on the main thread.  As an example, if you want to track a view event you might do something like this in your view controller:
```objective-c
- (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    
    [Tealium trackCallType:TealiumViewCall
                customData:nil
                    object:self];
}
```
The self being passed to the trackCallType:customData:object method is a UIViewController so accessing any info on that we need to do on the main thread.

The other UIKit object we regularly interact with is a UIWebview to execute and javascript tags Tealium is managing for your app.    This is what you see happing in the time profiler you have attached.  Depending on the number of tags you have each track call should be a small mount of time.  What you have highlighted in instruments is the webkit's usage over the course of 70 seconds.

What I would ask is how many track calls your doing during that time?  You said this is during interaction with a scrollview? Are you sending tracking evens as you scroll?  That is to say during one of the scrollview delegate call backs? If so you might be bombarding the system with a lot of calls that could be preformed after your scrolling in completed?

**Comment by iainsmith** [comment]
Thanks for the detailed reply.

All our `TealiumViewCall` look like so:
```
- (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];

    [Tealium trackCallType:TealiumViewCall
                customData:nil
                    object:self];
}

**Comment by iainsmith** [comment]
Thanks for the detailed reply.

None of our tracking events pass UIKit objects to Tealium, we always pass nil for the `object` parameter and our customData is a dictionary of plain NSStrings. There are also no `UIWebviews` in the app at this stage, so I don't see any reason for these calls to go through the main thread.

Our client wants to track when cells appear & has asked us to use `TealiumViewCall` type for these events. They use the time the event was sent to calculate the time spent on each cell.

Will changing from TealiumViewCall to TealiumEventCall change how the events are processed by your backend?

Do you have checks in place to see if you actually need to put work on the main thread or is it done for each event where the type is `TealiumViewCall`? If we were making calls using your example they would like something like this: 

```objc
- (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];

    // Wrapped in a dispatch_async
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
            [Tealium trackCallType:TealiumViewCall
                customData:@{@"key": @"value"}
                    object:nil];
    });
}
```

Would you expect that to call through to `[TealiumInternalConstants performBlockOnMainThread]`?

**Comment by ethyreal** [comment]
I just want to make sure I fully understand what you are trying to do.

You have a table view or collection view of some sort and you are sending:
```objective-c
[Tealium trackCallType:TealiumViewCall
                 customData:@{@"key": @"value"}
                           object:nil];
```
When each cell appears on the screen?

If you want smooth scrolling you need to do minimal work during each cells creation, this is of course why UIKit uses a cell queue paradigm and recycles views in a loop while you scroll.  If that is the case I would advice saving the timestamps for each view and dispatching them later. 

Regarding using ```dispatch_async``` this is the first thing every call into our library does so that should not ever be needed.

Regarding the web view, I think there was some confusion with how our library works.  We actually use a web view inside our library.  I is performant as it is strictly for processing javascript Tags, the actual work is done in web worker threads but passing data to the web view does need to happen on the main thread.  

This is likely the root reason for you seeing these main thread calls.   Also this is why we would advise against making track calls for every cell while scrolling.  The library has no way of knowing that you are doing all this inside of a scroll view.
